#!/bin/sh /etc/rc.common
# {# jinja-parse #}
INSTALL_PREFIX={{INSTALL_PREFIX}}

START=50

SERVICE_PID_FILE_BASE="/var/run/udhcpc"

NAME=debugnet

INTERFACES="{{ CONFIG_MANAGER_WANO_IFACE_LIST }}"
VLAN=4

start()
{
    for IF in $INTERFACES
    do
        # Skip non-existing interfaces
        [ ! -e /sys/class/net/$IF ] && continue

        VIF="${IF}.${VLAN}"
        [ -d "/sys/class/net/$VIF" ] || vconfig add $IF $VLAN

        SERVICE_PID_FILE=$SERVICE_PID_FILE_BASE-$VIF".pid"

        # Bring-up interfaces
        ifconfig $IF up
        ifconfig $VIF up
        start-stop-daemon -S -x /sbin/udhcpc -p $SERVICE_PID_FILE -b -m -- -s ${INSTALL_PREFIX}/bin/udhcpc.sh -f -S -i $VIF -C -o -O subnet
    done
}

stop()
{
    for IF in $INTERFACES
    do
        # Skip non-existing interfaces
        [ ! -e /sys/class/net/$IF ] && continue

        VIF="${IF}.${VLAN}"
        SERVICE_PID_FILE=$SERVICE_PID_FILE_BASEi-$VIF".pid"
        start-stop-daemon -K -x /sbin/udhcpc -p $SERVICE_PID_FILE
        rm $SERVICE_PID_FILE
        [ -d "/sys/class/net/$VIF" ] && vconfig rem $VIF
    done
}
