#!/bin/sh /etc/rc.common
# {# jinja-parse #}
INSTALL_PREFIX={{INSTALL_PREFIX}}

{% if CONFIG_PLATFORM_QCA_QSDK110 %}
START=74
{% else %}
START=99
{% endif %}

start()
{
    # Start OpenSync
    ${INSTALL_PREFIX}/bin/start.sh 2>&1 | logger -t start.sh
    start-stop-daemon -S -b -p /var/run/dm.pid -x ${INSTALL_PREFIX}/bin/dm
}

stop()
{
    # Stop OpenSync
    ${INSTALL_PREFIX}/bin/stop.sh 2>&1 | logger -t stop.sh
}
