#!/bin/sh /etc/rc.common

START=99

start()
{
    # Start OpenSync
    /usr/plume/bin/start.sh 2>&1 | logger -t start.sh
    start-stop-daemon -S -b -p /var/run/dm.pid -x /usr/plume/bin/dm
}

stop()
{
    # Stop OpenSync
    /usr/plume/bin/stop.sh 2>&1 | logger -t stop.sh
}
