#!/bin/sh /etc/rc.common
# {# jinja-parse #}
#
# OpenSync reference board specifics
#

INSTALL_PREFIX={{INSTALL_PREFIX}}

START=00

start()
{
    start-stop-daemon -S -b -x ${INSTALL_PREFIX}/bin/watchdog-kick.sh
}
